### ISSUE TITLE
extra steps needed to get readme instructions to work

### ISSUE THREAD

**Issue by fairchild** [flynn-archive/flynn-demo#15]
A few steps appear to be missing from the readme, assuming i do not have an abnormal system.
after `vagrant up && vagrant ssh` and `cd nodejs-example/`  the next sep is to push to the repos remote, _flynn vagrant@flynn:example_, however a host entry or ~/.ssh/config  needs to be made to have this work.  After putting an entry for flynn in the `etc/hosts` file, and accepting the unknown ssh_key to known_hosts, a password is required and when using vagrant\vagrant for user\pass it yields

```
vagrant@packer-virtualbox:/vagrant/nodejs-example$ git push flynn master
vagrant@flynn's password: 
fatal: 'example' does not appear to be a git repository
fatal: The remote end hung up unexpected
```

perhaps using a custom image, or basing the demos off of /vagrant, which could be mounted from the repo to the host would allow some more flexibility to ensure a consistently working system

**Comment by titanous** [comment]
Did you shutdown/`vagrant halt` after running make for the first time? I think gitreceive is keeping keys in /tmp currently which would cause the password problem after a reboot. If you run `make` again, it should work.

I'm in the process of getting everything into containers so that bootstrapping is much more robust (layer 0 is done already).
